#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PLACEHOLDER = "00000000-0000-0000-0000-000000000000";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(repoRoot, "backend/server/wrangler.toml");
const outputPath = resolve(repoRoot, "backend/server/wrangler.preprod.toml");

if (process.argv.includes("--help")) {
  console.log(`Usage: pnpm --filter cardano-tessera-backend configure:preprod -- <database-id>

Writes a git-ignored Wrangler config containing the operator's preprod D1 id.`);
  process.exit(0);
}

const databaseId = process.argv.slice(2).find((arg) => arg !== "--");
if (!databaseId || !UUID.test(databaseId) || databaseId === PLACEHOLDER) {
  throw new Error(
    "expected the non-placeholder UUID from `wrangler d1 create`",
  );
}

const source = readFileSync(sourcePath, "utf8");
const start = source.indexOf("[env.preprod]");
const end = source.indexOf("[env.mainnet]", start);
if (start < 0 || end < 0) {
  throw new Error("wrangler.toml has no bounded env.preprod block");
}

const block = source.slice(start, end);
const marker = `database_id = "${PLACEHOLDER}"`;
if (!block.includes(marker)) {
  throw new Error(
    "env.preprod no longer contains the expected database placeholder",
  );
}

const configured =
  "# Generated by scripts/configure-preprod.mjs; do not commit.\n" +
  source.slice(0, start) +
  block.replace(marker, `database_id = "${databaseId}"`) +
  source.slice(end);
writeFileSync(outputPath, configured, { mode: 0o600 });
console.log(outputPath);
